name: baseline
description: Baseline - Dopamine wellness lake ecosystem app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/day/
    - assets/backgrounds/dusk/
    - assets/backgrounds/night/
    - assets/animals/awake/day/
    - assets/animals/awake/dusk/
    - assets/animals/sleeping/day/
    - assets/animals/sleeping/dusk/
    - assets/animals/sleeping/night/
    - assets/shimmer/day/
    - assets/shimmer/dusk/
    - assets/shimmer/night/
    - assets/bonsai/day/
    - assets/bonsai/dusk/
    - assets/bonsai/night/
